### ISSUE TITLE
Goed gedaan!

### ISSUE THREAD

**Issue by vierzeven** [pieeet/ao-roc-dev#6]
Je hebt feedback gekregen van **mitjmitjmitj**
op:
```c
   <booleanAttribute key="M2_OFFLINE" value="false"/> 
```

URL: https://github.com/pieeet/ao-roc-dev/blob/master/rocdevcursussen/eclipse-launch-profiles/DevAppServer.launch

Feedback: Piet, jij bent goed bezig![](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"2290cd0cea46bb609e7df1da227926e6505732c3","path":"rocdevcursussen/eclipse-launch-profiles/DevAppServer.launch","reviewer":"mitjmitjmitj"}')

**Comment by pieeet** [comment]
:-)
